### ISSUE TITLE
Doer URI command

### ISSUE THREAD

**Issue by nefro85** [sygnowski/doer#18]
### Configuration
doer.yaml

```yaml
version: v1
kind: Config
params:
  broker: ${file:broker.properties}
  proto.descriptors: /path/to/1.desc, /path/to/2.desc
```

Workdir
```bash
> ls
doer.yaml #directory-based configuration file

```

### Samples of command usage:

- ```bash
  # drop messages from kafka
  > doer uri kafka://broker/topic/consumer-id?range=from_time=2022-01-01T12:00:00

- ```bash
  # put a message on kafka topic
  > doer uri kafka://broker/topic?value=my-value&key=my-key

- ```bash
  # decode an message
  > doer uri proto://message-name?base64=d2t1
