### ISSUE TITLE
Kafka Ingest Template - Random Generator

### ISSUE THREAD

**Issue by nefro85** [sygnowski/doer#35]
Add feature that will allow creating Kafka Ingest with random number generation.

```yaml
  value_sets:
    - name: my-set
      attributes:
        - T
      values:
        - [ "${rand=-30..60}.${rand=0..100}" ]
      repeat: 200000
```
